server:
  port: 8096

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
