spring.application.name=Shipyard Repair Planner

spring.datasource.url=jdbc:postgresql://localhost:5432/shipyard_repair
spring.datasource.username=shipyard_user
spring.datasource.password=shipyard_user29110L!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.messages.encoding=UTF-8

app.security.jwt.secret=${JWT_SECRET:change_me_to_a_long_random_secret_key_for_hs256_change_me}
app.security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
logging.pattern.correlation=[%X{traceId:-},%X{spanId:-}]
app.legacy-api.block-enabled=true
