spring.application.name=Shipyard Repair Planner

spring.datasource.url=jdbc:postgresql://localhost:5432/shipyard_repair
spring.datasource.username=shipyard_user
spring.datasource.password=shipyard_user29110L!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.messages.encoding=UTF-8