server:
  port: 8095

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: fleet-service
      auto-offset-reset: earliest

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
logging:
  pattern:
    correlation: "[%X{traceId:-},%X{spanId:-}] "
